### ISSUE TITLE
ERR PANO TOO LARGE

### ISSUE THREAD

**Issue by 18702738101** [krupkat/xpano#127] opened 2024-03-12 08:24 UTC
When I export a panoramic picture, the software reports an error:
ERR PANO TOO LARGE
Reset the adjustments through the edit menu.
![微信图片_20240312162017](https://github.com/krupkat/xpano/assets/32948664/05935e94-12ee-4ccb-8bfd-e2bbcc375457)

**Comment by przestaw** [comment] 2024-03-14 15:02
I can confirm issiue with `ERR PANO TOO LARGE` for 10+ JPEG photos. Did not run out of memory. I wouldnt mind if pano from multiple photos took long to export

**Comment by krupkat** [comment] 2024-03-14 18:58
Thanks for the reports!

Just to confirm, did you get a good result with a previous version of Xpano, or is this the first time you're testing the app now with the 0.18 version? I have added this check in 0.18 because previously the app was crashing for large panos.

I'll have a look and try to implement it so that the pano is exported at a maximum supported resolution (possibly selectable in the options).

If you don't mind sharing your pictures, I'd be happy to test the new approach on them, you can send me a link on email / matrix chat (links on https://krupkat.cz)

**Comment by przestaw** [comment] 2024-03-15 18:35
> I have added this check in 0.18 because previously the app was crashing for large panos.

Is this limitation of OpenCV or *some* engine in the app? I admit my photos were JPEGS ~18MPx each straight from camera with no edits [I was testing if your app will suit my needs]. 

If this is limitation of the app, please point me to the parts of code/module responsible for holding/handling of stiched panorama. Any information about algorithm/architecture of your app will be welcome.
I have no familiarity with OpenCV API [or GUI you have used] but I have *some* experience with bitmaps & graphics in boost/Qt soo... when I will have some free time I might try to help :)

Cheers

**Comment by krupkat** [comment] 2024-04-23 18:23
This is great, thanks a lot! :)

@przestaw
> Is this limitation of OpenCV or some engine in the app?

The error was coming  from OpenCV, but honestly I was not able to reproduce it when I tried recently... when I disable the max pano size and try some large pano (e.g. by rotating a perspective projection in so that it stretches a lot) I get an out of memory exception and surprisingly, the app survives, just cancelling the task.

**Comment by krupkat** [comment] 2024-04-29 19:49
the perspective projection (also called rectilinear) is especially bad for wide field of view images - more than 120 degrees and the stretching effect really kicks in, there is some description of this here (wide horizontal field of view):

https://www.cambridgeincolour.com/tutorials/image-projections.htm

I see some possible options:
 - detect this and cancel the stitch + show some warning
 - allow cropping to a smaller FoV during blending, using the dst_roi argument here: https://docs.opencv.org/4.9.0/d6/d4a/classcv_1_1detail_1_1Blender.html#a6d81cd6a0a2284de3ec7898409c7c0a8

**Comment by flightmansam** [comment] 2024-06-09 15:04
Could I request that you trigger github to release a new build? It would be smashing to have this feature added in the main builds section. 

Love the app!

**Comment by krupkat** [comment] 2024-06-10 18:42
Great to hear! I'd be curious to know what sizes / number of images you can get up to, feel free to share here or privately.

The new builds:
https://github.com/krupkat/xpano/releases/tag/pre-release-v0.19.0

**Comment by flightmansam** [comment] 2024-06-11 02:21
It eas just 6 very high res photos straight out of camera (6000x4000). The in camera panorama maker (Sony a6400) is absolutely garbage and it lowers the res by a butt load. And so I found your amazing app! It works so well now with the max size adjustment. Output file turned out quite alright!

https://cloud.flightmansam.id.au/index.php/s/sSyiaYiLSWZyR9T

**Comment by jsren** [comment] 2024-07-17 22:04
Can confirm I just ran a 48811 x 4294 8bpp panorama and it stitched no problem! This definitely fixes the problem. Thanks! 🙂

**Comment by jsren** [comment] 2024-07-17 22:07
+1 on the A6400 built-in panorama being awful, and this program being amazing!

**Comment by krupkat** [comment] 2024-07-27 13:14
Thanks for all your feedback, it is encouraging :)

I'll be releasing a new version soon where you'll be able to limit the max pano size in MPx, with the benefit that the app will automatically shrink the panorama to the selected MPx limit. I'll close this issue afterwards.

https://github.com/krupkat/xpano/tree/feature-max-pano-size

![image](https://github.com/user-attachments/assets/0e5e8686-7dba-4e10-9e96-3f451b67bd63)

**Closed** 2024-07-28 12:22 UTC
Labels: bug

**Comment by krupkat** [comment] 2024-07-28 19:18
@18702738101 @jsren @flightmansam @przestaw @Altonss 

Hopefuly this is fixed now, feel free to reopen.

**Comment by flightmansam** [comment] 2024-07-29 00:33
@krupkat You're a legend, thanks so much.
